=== tad1/pg_sa_lab4/offerts/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "Example Props",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "type":{
                "enum": ["Alchemist", "Elementarist", "Herbalist", "Mage"]   
            },
            "name":{
                "type":"string"
            },
            "potions":{
                "type":"array",
                "items": {
                    "type":"string",
                    "enum": ["Monday Potion", "Blast Potion of Energy", "Vitality Potion", "Potion of Instant Hangover", "Potion of Strenght", "Potion of mana"]
                }
            },
            "herbs":{
                "type":"array",
                "items": {
                    "type":"string",
                    "enum": ["Mytical Dandelion", "Grass", "Oregano", "Marshmallow", "Hyssop"]
                }
            },
            "essences":{
                "type":"array",
                "items": {
                    "type":"string",
                    "enum": ["Water Essence", "Light Essence", "Dark Essence", "Fire Essence", "Air Essence", "Earth Essence", "Sulfur Essence", "Mercury Essence", "Salt Essence"]
                }
            },
            "prices":{
                "type":"array",
                "items": {
                    "type":"integer"
                }
            },
            "number":{
                "type":"array",
                "items": {
                    "type":"integer"
                }
            },
            "money":{
                "type":"integer"
            }
        },
        "allOf": [
            {
                "required":["type"],
                "if": {
                    "properties": {"type":{"const": "Alchemist"}}
                },
                "then": {
                    "required": ["potions", "prices", "number"],
                    "not": { "required": ["essences", "money"]}
                }
            },
            {
                "required":["type"],
                "if": {
                    "properties": {"type":{"const": "Herbalist"}}
                },
                "then": {
                    "required": ["herbs", "prices", "number"],
                    "not": { "required": ["potions", "essences", "money"]}
                }
            },
            {
                "required":["type"],
                "if": {
                    "properties": {"type":{"const": "Elementarist"}}
                },
                "then": {
                    "required": ["essences", "prices", "number"],
                    "not": { "required": ["potions", "herbs", "money"]}
                }
            },
            {
                "required":["type"],
                "if": {
                    "properties": {"type":{"enum": ["Elementarist"]}}
                },
                "then": {
                    "required": ["money"],
                    "not": { "required": ["prices", "number"]}
                }
            }
        ]
    }
}

=== tad1/pg_sa_lab4/offerts/case1.json
[
    {
        "type": "Alchemist",
        "name": "Adam",
        "potions": ["Potion of mana", "Monday Potion", "Blast Potion of Energy"],
        "number": [2, 3, 2],
        "prices": [2,3,2]
    },
    {
        "type": "Herbalist",
        "name": "Agel",
        "herbs": ["Grass", "Marshmallow", "Mytical Dandelion"],
        "number": [2, 1, 2],
        "prices": [2,3,4]
    },
    {
        "type": "Mage",
        "name": "Mana",
        "herbs": ["Grass"],
        "potions": ["Monday Potion", "Blast Potion of Energy", "Blast Potion of Energy"],
        "essences": [],
        "money": 12
    },
    {
        "type": "Mage",
        "name": "Range",
        "herbs": ["Grass"],
        "potions": ["Monday Potion"],
        "essences": [],
        "money": 10
    }
]

=== tad1/pg_sa_lab4/offerts/case2.json
[
    {
        "type": "Alchemist",
        "name": "Adam",
        "potions": ["Potion of mana", "Monday Potion", "Blast Potion of Energy"],
        "number": [2, 1, 2],
        "prices": [2,3,4]
    },
    {
        "type": "Herbalist",
        "name": "Agel",
        "herbs": ["Grass", "Marshmallow", "Mytical Dandelion"],
        "number": [2, 1, 2],
        "prices": [2,3,4]
    },
    {
        "type": "Elementarist",
        "name": "HighPrices",
        "essences": ["Air Essence", "Dark Essence", "Earth Essence", "Fire Essence"],
        "prices": [999,999,999,999],
        "number": [10, 10, 10, 10]
    },
    {
        "type": "Mage",
        "name": "Mana",
        "herbs": ["Grass"],
        "potions": ["Monday Potion", "Blast Potion of Energy", "Blast Potion of Energy"],
        "essences": ["Air Essence"],
        "money": 10
    }
]
